/* Generated By:JavaCC: Do not edit this line. EdifParserCoreConstants.java */
/*
 * Copyright (c) 2008 Brigham Young University
 * 
 * This file is part of the BYU EDIF Tools.
 * 
 * BYU EDIF Tools is free software: you may redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or (at your option) any
 * later version.
 * 
 * BYU EDIF Tools is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 * 
 * A copy of the GNU General Public License is included with the BYU EDIF Tools.
 * It can be found at /edu/byu/edif/doc/gpl2.txt. You may also get a copy of the
 * license at <http://www.gnu.org/licenses/>.
 * 
 */
package edu.byu.ece.edif.util.parse;

public interface EdifParserCoreConstants {

    int EOF = 0;

    int ANGLE = 6;

    int BEHAVIOR = 7;

    int CALCULATED = 8;

    int CAPACITANCE = 9;

    int CENTERCENTER = 10;

    int CENTERLEFT = 11;

    int CENTERRIGHT = 12;

    int CHARGE = 13;

    int CONDUCTANCE = 14;

    int CURRENT = 15;

    int DISTANCE = 16;

    int DOCUMENT = 17;

    int ENERGY = 18;

    int EXTEND = 19;

    int FLUX = 20;

    int FREQUENCY = 21;

    int GENERIC = 22;

    int GRAPHIC = 23;

    int INDUCTANCE = 24;

    int INOUT = 25;

    int INPUT = 26;

    int LOGICMODEL = 27;

    int LOWERCENTER = 28;

    int LOWERLEFT = 29;

    int LOWERRIGHT = 30;

    int MASKLAYOUT = 31;

    int MASS = 32;

    int MEASURED = 33;

    int MX = 34;

    int MXR90 = 35;

    int MY = 36;

    int MYR90 = 37;

    int NETLIST = 38;

    int OUTPUT = 39;

    int PCBLAYOUT = 40;

    int POWER = 41;

    int R0 = 42;

    int R180 = 43;

    int R270 = 44;

    int R90 = 45;

    int REQUIRED = 46;

    int RESISTANCE = 47;

    int RIPPER = 48;

    int ROUND = 49;

    int SCHEMATIC = 50;

    int STRANGER = 51;

    int SYMBOLIC = 52;

    int TEMPERATURE = 53;

    int TIE = 54;

    int TIME = 55;

    int TRUNCATE = 56;

    int UPPERCENTER = 57;

    int UPPERLEFT = 58;

    int UPPERRIGHT = 59;

    int VOLTAGE = 60;

    int ACLOAD = 61;

    int AFTER = 62;

    int ANNOTATE = 63;

    int APPLY = 64;

    int ARC = 65;

    int ARRAY = 66;

    int ARRAYMACRO = 67;

    int ARRAYRELATEDINFO = 68;

    int ARRAYSITE = 69;

    int ATLEAST = 70;

    int ATMOST = 71;

    int AUTHOR = 72;

    int BASEARRAY = 73;

    int BECOMES = 74;

    int BETWEEN = 75;

    int BOOLEAN = 76;

    int BOOLEANDISPLAY = 77;

    int BOOLEANMAP = 78;

    int BORDERPATTERN = 79;

    int BORDERWIDTH = 80;

    int BOUNDINGBOX = 81;

    int CELL = 82;

    int CELLREF = 83;

    int CELLTYPE = 84;

    int CHANGE = 85;

    int CIRCLE = 86;

    int COLOR = 87;

    int COMMENT = 88;

    int COMMENTGRAPHICS = 89;

    int COMPOUND = 90;

    int CONNECTLOCATION = 91;

    int CONTENTS = 92;

    int CORNERTYPE = 93;

    int CRITICALITY = 94;

    int CURRENTMAP = 95;

    int CURVE = 96;

    int CYCLE = 97;

    int DATAORIGIN = 98;

    int DCFANINLOAD = 99;

    int DCFANOUTLOAD = 100;

    int DCMAXFANIN = 101;

    int DCMAXFANOUT = 102;

    int DELAY = 103;

    int DELTA = 104;

    int DERIVATION = 105;

    int DESIGN = 106;

    int DESIGNATOR = 107;

    int DIFFERENCE = 108;

    int DIRECTION = 109;

    int DISPLAY = 110;

    int DOMINATES = 111;

    int DOT = 112;

    int DURATION = 113;

    int E = 114;

    int EDIF = 115;

    int EDIFLEVEL = 116;

    int EDIFVERSION = 117;

    int ENCLOSUREDISTANCE = 118;

    int ENDTYPE = 119;

    int ENTRY = 120;

    int EVENT = 121;

    int EXACTLY = 122;

    int EXTERNAL = 123;

    int FABRICATE = 124;

    int FALSE = 125;

    int FIGURE = 126;

    int FIGUREAREA = 127;

    int FIGUREGROUP = 128;

    int FIGUREGROUPOBJECT = 129;

    int FIGUREGROUPOVERRIDE = 130;

    int FIGUREGROUPREF = 131;

    int FIGUREPERIMETER = 132;

    int FIGUREWIDTH = 133;

    int FILLPATTERN = 134;

    int FOLLOW = 135;

    int FORBIDDENEVENT = 136;

    int GLOBALPORTREF = 137;

    int GREATERTHAN = 138;

    int GRIDMAP = 139;

    int IGNORE = 140;

    int INCLUDEFIGUREGROUP = 141;

    int INITIAL = 142;

    int INSTANCE = 143;

    int INSTANCEBACKANNOTATE = 144;

    int INSTANCEGROUP = 145;

    int INSTANCEMAP = 146;

    int INSTANCEREF = 147;

    int INTEGER = 148;

    int INTEGERDISPLAY = 149;

    int INTERFACE = 150;

    int INTERFIGUREGROUPSPACING = 151;

    int INTERSECTION = 152;

    int INTRAFIGUREGROUPSPACING = 153;

    int INVERSE = 154;

    int ISOLATED = 155;

    int JOINED = 156;

    int JUSTIFY = 157;

    int KEYWORDDISPLAY = 158;

    int KEYWORDLEVEL = 159;

    int KEYWORDMAP = 160;

    int LESSTHAN = 161;

    int LIBRARY = 162;

    int LIBRARYREF = 163;

    int LISTOFNETS = 164;

    int LISTOFPORTS = 165;

    int LOADDELAY = 166;

    int LOGICASSIGN = 167;

    int LOGICINPUT = 168;

    int LOGICLIST = 169;

    int LOGICMAPINPUT = 170;

    int LOGICMAPOUTPUT = 171;

    int LOGICONEOF = 172;

    int LOGICOUTPUT = 173;

    int LOGICPORT = 174;

    int LOGICREF = 175;

    int LOGICVALUE = 176;

    int LOGICWAVEFORM = 177;

    int MAINTAIN = 178;

    int MATCH = 179;

    int MEMBER = 180;

    int MINOMAX = 181;

    int MINOMAXDISPLAY = 182;

    int MNM = 183;

    int MULTIPLEVALUESET = 184;

    int MUSTJOIN = 185;

    int NAME = 186;

    int NET = 187;

    int NETBACKANNOTATE = 188;

    int NETBUNDLE = 189;

    int NETDELAY = 190;

    int NETGROUP = 191;

    int NETMAP = 192;

    int NETREF = 193;

    int NOCHANGE = 194;

    int NONPERMUTABLE = 195;

    int NOTALLOWED = 196;

    int NOTCHSPACING = 197;

    int NUMBER = 198;

    int NUMBERDEFINITION = 199;

    int NUMBERDISPLAY = 200;

    int OFFPAGECONNECTOR = 201;

    int OFFSETEVENT = 202;

    int OPENSHAPE = 203;

    int ORIENTATION = 204;

    int ORIGIN = 205;

    int OVERHANGDISTANCE = 206;

    int OVERLAPDISTANCE = 207;

    int OVERSIZE = 208;

    int OWNER = 209;

    int PAGE = 210;

    int PAGESIZE = 211;

    int PARAMETER = 212;

    int PARAMETERASSIGN = 213;

    int PARAMETERDISPLAY = 214;

    int PATH = 215;

    int PATHDELAY = 216;

    int PATHWIDTH = 217;

    int PERMUTABLE = 218;

    int PHYSICALDESIGNRULE = 219;

    int PLUG = 220;

    int POINT = 221;

    int POINTDISPLAY = 222;

    int POINTLIST = 223;

    int POLYGON = 224;

    int PORT = 225;

    int PORTBACKANNOTATE = 226;

    int PORTBUNDLE = 227;

    int PORTDELAY = 228;

    int PORTGROUP = 229;

    int PORTIMPLEMENTATION = 230;

    int PORTINSTANCE = 231;

    int PORTLIST = 232;

    int PORTLISTALIAS = 233;

    int PORTMAP = 234;

    int PORTREF = 235;

    int PROGRAM = 236;

    int PROPERTY = 237;

    int PROPERTYDISPLAY = 238;

    int PROTECTIONFRAME = 239;

    int PT = 240;

    int RANGEVECTOR = 241;

    int RECTANGLE = 242;

    int RECTANGLESIZE = 243;

    int RENAME = 244;

    int RESOLVES = 245;

    int SCALE = 246;

    int SCALEX = 247;

    int SCALEY = 248;

    int SECTION = 249;

    int SHAPE = 250;

    int SIMULATE = 251;

    int SIMULATIONINFO = 252;

    int SINGLEVALUESET = 253;

    int SITE = 254;

    int SOCKET = 255;

    int SOCKETSET = 256;

    int STATUS = 257;

    int STEADY = 258;

    int STRING = 259;

    int STRINGDISPLAY = 260;

    int STRONG = 261;

    int SYMBOL = 262;

    int SYMMETRY = 263;

    int TABLE = 264;

    int TABLEDEFAULT = 265;

    int TECHNOLOGY = 266;

    int TEXTHEIGHT = 267;

    int TIMEINTERVAL = 268;

    int TIMESTAMP = 269;

    int TIMING = 270;

    int TRANSFORM = 271;

    int TRANSITION = 272;

    int TRIGGER = 273;

    int TRUE = 274;

    int UNCONSTRAINED = 275;

    int UNDEFINED = 276;

    int UNION = 277;

    int UNIT = 278;

    int UNUSED = 279;

    int USERDATA = 280;

    int VERSION = 281;

    int VIEW = 282;

    int VIEWLIST = 283;

    int VIEWMAP = 284;

    int VIEWREF = 285;

    int VIEWTYPE = 286;

    int VISIBLE = 287;

    int VOLTAGEMAP = 288;

    int WAVEVALUE = 289;

    int WEAK = 290;

    int WEAKJOINED = 291;

    int WHEN = 292;

    int WRITTEN = 293;

    int ABS = 294;

    int AND = 295;

    int CEILING = 296;

    int CONCAT = 297;

    int CONSTANT = 298;

    int CONSTRAINT = 299;

    int DIVIDE = 300;

    int EQUAL = 301;

    int FIX = 302;

    int FLOOR = 303;

    int INCREASING = 304;

    int MAX = 305;

    int MIN = 306;

    int MOD = 307;

    int NEGATE = 308;

    int NOT = 309;

    int OR = 310;

    int POINTSUBTRACT = 311;

    int POINTSUM = 312;

    int PRODUCT = 313;

    int STRICTLYINCREASING = 314;

    int SUBTRACT = 315;

    int SUM = 316;

    int VARIABLE = 317;

    int XCOORD = 318;

    int XOR = 319;

    int YCOORD = 320;

    int INTEGER_TOK = 321;

    int STRING_TOK = 322;

    int IDENTIFIER = 323;

    int LETTER = 324;

    int DIGIT = 325;

    int LBR = 326;

    int RBR = 327;

    int DEFAULT = 0;

    String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\f\"", "\"ANGLE\"", "\"BEHAVIOR\"",
            "\"CALCULATED\"", "\"CAPACITANCE\"", "\"CENTERCENTER\"", "\"CENTERLEFT\"", "\"CENTERRIGHT\"", "\"CHARGE\"",
            "\"CONDUCTANCE\"", "\"CURRENT\"", "\"DISTANCE\"", "\"DOCUMENT\"", "\"ENERGY\"", "\"EXTEND\"", "\"FLUX\"",
            "\"FREQUENCY\"", "\"GENERIC\"", "\"GRAPHIC\"", "\"INDUCTANCE\"", "\"INOUT\"", "\"INPUT\"",
            "\"LOGICMODEL\"", "\"LOWERCENTER\"", "\"LOWERLEFT\"", "\"LOWERRIGHT\"", "\"MASKLAYOUT\"", "\"MASS\"",
            "\"MEASURED\"", "\"MX\"", "\"MXR90\"", "\"MY\"", "\"MYR90\"", "\"NETLIST\"", "\"OUTPUT\"", "\"PCBLAYOUT\"",
            "\"POWER\"", "\"R0\"", "\"R180\"", "\"R270\"", "\"R90\"", "\"REQUIRED\"", "\"RESISTANCE\"", "\"RIPPER\"",
            "\"ROUND\"", "\"SCHEMATIC\"", "\"STRANGER\"", "\"SYMBOLIC\"", "\"TEMPERATURE\"", "\"TIE\"", "\"TIME\"",
            "\"TRUNCATE\"", "\"UPPERCENTER\"", "\"UPPERLEFT\"", "\"UPPERRIGHT\"", "\"VOLTAGE\"", "\"acLoad\"",
            "\"after\"", "\"annotate\"", "\"apply\"", "\"arc\"", "\"array\"", "\"arrayMacro\"", "\"arrayRelatedInfo\"",
            "\"arraySite\"", "\"atLeast\"", "\"atMost\"", "\"author\"", "\"baseArray\"", "\"becomes\"", "\"between\"",
            "\"boolean\"", "\"booleanDisplay\"", "\"booleanMap\"", "\"borderPattern\"", "\"borderWidth\"",
            "\"boundingBox\"", "\"cell\"", "\"cellRef\"", "\"cellType\"", "\"change\"", "\"circle\"", "\"color\"",
            "\"comment\"", "\"commentGraphics\"", "\"compound\"", "\"connectLocation\"", "\"contents\"",
            "\"cornerType\"", "\"criticality\"", "\"currentMap\"", "\"curve\"", "\"cycle\"", "\"dataOrigin\"",
            "\"dcFaninLoad\"", "\"dcFanoutLoad\"", "\"dcMaxFanin\"", "\"dcMaxFanout\"", "\"delay\"", "\"delta\"",
            "\"derivation\"", "\"design\"", "\"designator\"", "\"difference\"", "\"direction\"", "\"display\"",
            "\"dominates\"", "\"dot\"", "\"duration\"", "\"e\"", "\"edif\"", "\"edifLevel\"", "\"edifVersion\"",
            "\"enclosureDistance\"", "\"endType\"", "\"entry\"", "\"event\"", "\"exactly\"", "\"external\"",
            "\"fabricate\"", "\"false\"", "\"figure\"", "\"figureArea\"", "\"figureGroup\"", "\"figureGroupObject\"",
            "\"figureGroupOverride\"", "\"figureGroupRef\"", "\"figurePerimeter\"", "\"figureWidth\"",
            "\"fillPattern\"", "\"follow\"", "\"forbiddenEvent\"", "\"globalPortref\"", "\"greaterThan\"",
            "\"gridMap\"", "\"ignore\"", "\"includeFigureGroup\"", "\"initial\"", "\"instance\"",
            "\"instanceBackAnnotate\"", "\"instanceGroup\"", "\"instanceMap\"", "\"instanceRef\"", "\"integer\"",
            "\"integerDisplay\"", "\"interface\"", "\"interFigureGroupSpacing\"", "\"intersection\"",
            "\"intraFigureGroupSpacing\"", "\"inverse\"", "\"isolated\"", "\"joined\"", "\"justify\"",
            "\"keywordDisplay\"", "\"keywordLevel\"", "\"keywordMap\"", "\"lessThan\"", "\"library\"",
            "\"libraryRef\"", "\"listofNets\"", "\"listOfPorts\"", "\"loadDelay\"", "\"logicAssign\"",
            "\"logicInput\"", "\"logicList\"", "\"logicMapinput\"", "\"logicMapOutput\"", "\"logicOneOf\"",
            "\"logicOutput\"", "\"logicPort\"", "\"logicRef\"", "\"logicValue\"", "\"logicWaveform\"", "\"maintain\"",
            "\"match\"", "\"member\"", "\"miNoMax\"", "\"miNoMaxDisplay\"", "\"mnm\"", "\"multipleValueSet\"",
            "\"mustJoin\"", "\"name\"", "\"net\"", "\"netBackAnnotate\"", "\"netBundle\"", "\"netDelay\"",
            "\"netGroup\"", "\"netMap\"", "\"netRef\"", "\"noChange\"", "\"nonPermutable\"", "\"notAllowed\"",
            "\"notchSpacing\"", "\"number\"", "\"numberDefinition\"", "\"numberDisplay\"", "\"offPageConnector\"",
            "\"offsetEvent\"", "\"openShape\"", "\"orientation\"", "\"origin\"", "\"overhangDistance\"",
            "\"overlapDistance\"", "\"oversize\"", "\"owner\"", "\"page\"", "\"pageSize\"", "\"parameter\"",
            "\"parameterAssign\"", "\"parameterDisplay\"", "\"path\"", "\"pathDelay\"", "\"pathWidth\"",
            "\"permutable\"", "\"physicalDesignRule\"", "\"plug\"", "\"point\"", "\"pointDisplay\"", "\"pointList\"",
            "\"polygon\"", "\"port\"", "\"portBackAnnotate\"", "\"portBundle\"", "\"portDelay\"", "\"portGroup\"",
            "\"portImplementation\"", "\"portInstance\"", "\"portList\"", "\"portListAlias\"", "\"portMap\"",
            "<PORTREF>", "\"program\"", "\"property\"", "\"propertyDisplay\"", "\"protectionFrame\"", "\"pt\"",
            "\"rangeVector\"", "\"rectangle\"", "\"rectangleSize\"", "\"rename\"", "\"resolves\"", "\"scale\"",
            "\"scalex\"", "\"scaley\"", "\"section\"", "\"shape\"", "\"simulate\"", "\"simulationInfo\"",
            "\"singleValueSet\"", "\"site\"", "\"socket\"", "\"socketSet\"", "\"status\"", "\"steady\"", "\"string\"",
            "\"stringDisplay\"", "\"strong\"", "\"symbol\"", "\"symmetry\"", "\"table\"", "\"tableDefault\"",
            "\"technology\"", "\"textheight\"", "\"timeinterval\"", "\"timeStamp\"", "\"timing\"", "\"transform\"",
            "\"transition\"", "\"trigger\"", "\"true\"", "\"unconstrained\"", "\"undefined\"", "\"union\"", "\"unit\"",
            "\"unused\"", "\"userData\"", "\"version\"", "\"view\"", "\"viewList\"", "\"viewMap\"", "\"viewRef\"",
            "\"viewType\"", "\"visible\"", "\"voltageMap\"", "\"waveValue\"", "\"weak\"", "\"weakJoined\"", "\"when\"",
            "\"written\"", "\"abs\"", "\"and\"", "\"ceiling\"", "\"concat\"", "\"constant\"", "\"constraint\"",
            "\"divide\"", "\"equal\"", "\"fix\"", "\"floor\"", "\"increasing\"", "\"max\"", "\"min\"", "\"mod\"",
            "\"negate\"", "\"not\"", "\"or\"", "\"pointSubtract\"", "\"pointSum\"", "\"product\"",
            "\"strictlyIncreasing\"", "\"subtract\"", "\"sum\"", "\"variable\"", "\"xCoord\"", "\"xor\"", "\"yCoord\"",
            "<INTEGER_TOK>", "<STRING_TOK>", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "\"(\"", "\")\"", };

}
