ROOT = ../../../../..

EXE=byucc.edif.libraries.xilinx.test.Edif2XilinxNameTest

include ${ROOT}/byucc/edif/config.mk

CLASSPATH=${CLASSPATHALL}

JSRCS = ${wildcard *.java}
JCLASS = ${JSRCS:%.java=%.class}


include ${ROOT}/byucc/edif/common.mk



